### ISSUE TITLE
re-drawing on resize

### ISSUE THREAD

**Issue by masoudelahi** [probil/vue-moveable#116]
#8 
I have same problem,
version: 1.5.0
container have full width,
when i change width of side element programmatically that happens again

**Comment by probil** [comment]
Hey @masoudelahi 👋 
Could you please provide codesandbox reproducing the issue? You can take the demo project mentioned in README

**Comment by probil** [comment]
Couldn't reproduce. It works just fine for me. Closed because of inactivity.
