### ISSUE TITLE
Events doesn't seem to be bound correctly

### ISSUE THREAD

**Issue by giuliogatto** [probil/vue-moveable#125]
Hello,
I am having an issue with events:
```
 @drag-end="console.log('end')"
 @dragstart="console.log('start')"
```
Gives me an error:
_"dragend" is emitted in component <Moveable> but the handler is registered for "dragEnd". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "drag-end" instead of "dragEnd"._

And no callback is executed. 
BTW: thank you for the library!

**Comment by probil** [comment]
Sounds like a bug, I'll check it.
Thanks @giuliogatto for reporting

**Comment by chonsser** [comment]
According to [Vue's docs](https://vuejs.org/v2/guide/components-custom-events.html) the events should support kebab-case. I think we should deprecate the `camelCase` in the near future to comply with Vue's naming convention. 

I've made a [pull request](https://github.com/probil/vue-moveable/pull/128) which brings support for the kebab-case events. Ping @probil

**Comment by probil** [comment]
kebab-case events support lended in `v1.7.2`, camelCase events are still supported (till the next major version). Thanks @chonsser 

@giuliogatto Could you please confirm that the issue is fixed for you?
