### ISSUE TITLE
keepRatio, for all resize circles? 

### ISSUE THREAD

**Issue by stefanaz** [probil/vue-moveable#36]
Is it possible to apply keepRatio for all resize circles, currently it does work only for the corner circles. 
Or is it possible to hide some of the resize circles?

**Comment by probil** [comment]
I think you can archive it use custom css.
https://github.com/daybrush/moveable/blob/master/handbook/handbook.md#toc-custom-css

You can also ask in original repo
https://github.com/daybrush/moveable/issues

**Comment by stefanaz** [comment]
@probil  thanks!
