### ISSUE TITLE
stick to parent size? 

### ISSUE THREAD

**Issue by stefanaz** [probil/vue-moveable#37]
Is it possible to limit element movements by a parent container size?

**Comment by stefanaz** [comment]
@probil  thanks for pushing that on. I have found bounds property on the original moveable documentation site. https://daybrush.com/moveable/release/latest/doc/Moveable.html#bounds
But it seems to not be yet ported ? Or I am using that not correctly? Could you help please? 

I try like that: 
<Moveable
    .....
    :bounds="{ left: 220, right: 1000, top: 0, bottom: 1000}">
    .....
</Moveable>

**Comment by probil** [comment]
Directly related to #31

**Comment by probil** [comment]
Released as part of v1.0.0
