### ISSUE TITLE
hide / show / hide blue line helpers. 

### ISSUE THREAD

**Issue by stefanaz** [probil/vue-moveable#41]
How could I with Vue hide and show line helpers? 

I have a few elements, and want sometimes remove all moveable functionality. Like it will be not draggable, not resiazable, not wrapable and so...  I can do that just added moveable.draggable="false", moveable.scalable="false" ... But, blue line-helpers are still there. 

My problem is that div with class name "moveable-control-box" which contains all line/point helpers to drag/resize/wrap element is added directly into the body tag. And I do not know how can I access and style correct "moveable-control-box" element within Vue.  

Do you have some ideas?

**Comment by stefanaz** [comment]
with property container: document.getElementById('my-div'),  fixed, and particularly  not relevant any more. I'll close it.

**Comment by donley828** [comment]
hi,how do you solve it

**Comment by zhishaofei3** [comment]
hi,how do you solve it ?

**Comment by fs-ses-tatsuya-matsunawa** [comment]
hi,how do you solve it ?
