### ISSUE TITLE
How to get the relation of moveable with moveable-control-box？

### ISSUE THREAD

**Issue by zhangweibo123** [probil/vue-moveable#51]
i have more vue-moveable，how to find which moveable-control-box when i click moveable？

**Comment by stefanaz** [comment]
had a same issue recently. The best way which I've found is: 
-- wrap your vue-moveable into div. Add him id or class. 
-- in your moveable config, specify container (div from the first step) which is related to your vue-moveable item like this : 
`container: document.getElementById('container_id') ` 

Then you will get: 

`<div id='container1'>`
   `    <vue-moveable />`
   `    <moveable-control-box />`
` </div>` 




From such order it is clear now which moveable-control-box belongs to vue-moveable.

**Comment by katOstrynska** [comment]
It does not work when there is more than one <Moveable> components, like this:
`<div class="container">
   <Moveable />
</div>
<div class="container">
   <Moveable />
</div>
<div class="container">
   <Moveable />
</div>`

then moveable-control-boxes does not render at all

**Comment by stefanaz** [comment]
@katOstrynska 
works for me like this: 

```
<div class="container">
   <Moveable id="item_1" />
   <Moveable id="item_2" />
</div>
```

for each Moveable item: 
```
v-bind="moveable_conf"
```
```
moveable_conf = {
...
  container: document.getElementById('item_'+index),
...
}
```

Hope this help)

**Comment by stefanaz** [comment]
@probil  I think it is this: 
![Bildschirmfoto 2019-10-23 um 16 47 33](https://user-images.githubusercontent.com/8876063/67405325-e4059400-f5b4-11e9-8025-c44d9424df29.png)

**Comment by stefanaz** [comment]
this does not work for me any more (since a new version was uploaded): 
`container: document.getElementById('container_id')`

@probil , I am also interested now, how to define connections between moveable and it's moveable-control-box. Do you have some ideas?

**Comment by stefanaz** [comment]
For example I want to change color of the blue lines on hover at the moveable item. I need to know then how to access "moveable-control-box". 

In case of multiple items it becomes not clear. 
The hard case comes also when item redraw, 'moveable-control-box' also redraws. And then it is not possible to find it even with a child index.

**Comment by probil** [comment]
```vue
      <Moveable
        ref="moveable"
      />
```
then (for example in `mounted` hook)
```js
this.$refs.moveable.moveable.innerMoveable.base
```
I'll add a shortcut for it later
<img width="546" alt="Screen Shot 2019-10-23 at 18 07 56" src="https://user-images.githubusercontent.com/6773202/67407368-0ea91a00-f5c0-11e9-8672-eb7b3ce8b9b9.png">

**Comment by zhangweibo123** [comment]
@probil  ref="moveable"   Should this parameter be updated before it can be used？


![image](https://user-images.githubusercontent.com/24311876/67447627-0f38c380-f647-11e9-8b0a-b79d7a430277.png)

**Comment by katOstrynska** [comment]
My main problem is that when i have image in movable element, blue control box has height of paragraph and width of 0. I figured, that if i will give movable element width and height (in scoped styles), then blue control box will be the same width and height as my movable element. I want to dynamically bind style to movable element, but it just do not show. Only movable transforms are binded, not my values. I tried adding width and height inline values to movable, but style doesn't reds it.

**Comment by katOstrynska** [comment]
@stefanaz yes! thank You, it worked; when I was setting the style as :width="item.width" it did not work; i tried bind :style, but i was clearly doing something wrong bc it didn't wokr. But now it works, thanks ;)

**Comment by probil** [comment]
`className` props allows to add custom class to the control box so there is at least one more way to achieve that.

BTW, @stefanaz is the issue still relevant?

**Comment by katOstrynska** [comment]
I have got problem with moveable-control-box also - when I mount my element I set moveable-control-box style (width, height, left, top, translate) the same as my element's, and it works. However, I am trying to do this when I stop my scale event and it does not work. I am using currentTarget:

my kandleScaleEnd method:

`currentTarget.innerMoveable.preactMoveable.base.style.width = this.el.getRect.width;
                currentTarget.innerMoveable.preactMoveable.base.style.height = this.el.getRect.height;
                currentTarget.innerMoveable.preactMoveable.base.style.left = this.el.getRect.left;
                currentTarget.innerMoveable.preactMoveable.base.style.top = this.el.getRect.top;
                currentTarget.innerMoveable.preactMoveable.base.style.transform = 'none';`

**Comment by probil** [comment]
@katOstrynska sounds like not directly related to the issue.
```js
currentTarget.innerMoveable.preactMoveable.base.style.transform = 'none';
```
Scale uses `transform` so when you set it to `none` it doesn't work. Scaled width is not the same as element width. I suppose you need you need to set transform as well

---

Closing because original question is seems to be resolved. Please create a new issue if you have any other questions
