### ISSUE TITLE
Container boundaries

### ISSUE THREAD

**Issue by ibadass** [probil/vue-moveable#60]
@probil How to handle bounds, I want my moveable object can't get out of the parent container, is that possible ?

**Comment by probil** [comment]
Hi @ibadass 👋 
Thanks for your issue. 
Have you tried `bounds`?

```vue
<Moveable :bounds="{ left: 0, right: 1000, top: 0, bottom: 1000};">
```
https://daybrush.com/moveable/release/latest/doc/Moveable.html#bounds

**Comment by ibadass** [comment]
Hi @probil,

I tried bounds option but it doesn't seems to work.
On "mounted" function, get the dimension of my container, and I apply on the bounds options (right and bottom), but when I add a new moveable object, I can drag it over the container.
Here a [codesandbox](https://codesandbox.io/s/vue-material-also-works-on-the-right-side-dgn27) to see my issue.

**Comment by Avyiel** [comment]
I'm having a similar issue, where `bounds` isn't constraining the moveable element. Any specific way to use it, other than in the `v-bind` object or as a prop `:bounds`?

**Comment by andreasvirkus** [comment]
Same issue here

**Comment by ibadass** [comment]
Hi @probil,

I updated my codesandbox with ` :bounds="{ left: 0, right: 1000, top: 0, bottom: 1000};"` and the issue is still here, do I "play" with z-index to resolve this issue ?

**Comment by andreasvirkus** [comment]
I had to set both `dragArea` and `snappable` to `true` and got it working then! Hope that helps @ibadass @Avyiel

**Comment by ibadass** [comment]
Hi @andreasvirkus, I add `snappable` and `dragArea` to true, but I always can move my moveable object all over the page instead the target area (see my [codebox](https://codesandbox.io/s/vue-material-also-works-on-the-right-side-dgn27))

**Comment by andreasvirkus** [comment]
> @probil I think you can close this issue.

You can close it yourself as well (right next to the Comment button)
