### ISSUE TITLE
Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by AsheKR** [probil/vue-moveable#63]
![image](https://user-images.githubusercontent.com/42999044/68444946-cb83b380-021b-11ea-8d8f-df7bc3082fcd.png)

Can't use it on the nuxt?

**Comment by razukc** [comment]
> ![image](https://user-images.githubusercontent.com/42999044/68444946-cb83b380-021b-11ea-8d8f-df7bc3082fcd.png)
> 
> Can't use it on the nuxt?

Either wrap your component in` no-ssr` or set `mode` to `client` in your plugin file
