### ISSUE TITLE
Fonts scale

### ISSUE THREAD

**Issue by katOstrynska** [probil/vue-moveable#72]
I have a problem with scalling texts - i would like to have defined moveable box and in there some text. When scalling, I want box scalling, not text. Now Text is scalling to, which breaks font-size.
Can I get this with Moveable?

**Comment by probil** [comment]
HI, @katOstrynska 👋 
Thanks for your issue. 

Just use `resizable` instead of `scalable`

**Comment by katOstrynska** [comment]
I will, thank You
