### ISSUE TITLE
vue-moveable with TS

### ISSUE THREAD

**Issue by hvilppu** [probil/vue-moveable#74]
I got:
Error	TS7016	(TS) Could not find a declaration file for module 'vue-moveable'. 'E:/project/node_modules/vue-moveable/dist/lib/VueMoveable.common.js' implicitly has an 'any' type.
  Try `npm install @types/vue-moveable` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-moveable';`	E:\projec (tsconfig or jsconfig project)	

when I try import vue-moveable at project with typescipt.

I just try:
import Moveable from 'vue-moveable';

...
How I should do this on project with type script?

**Comment by newcat** [comment]
As a temp fix you can add `// @ts-ignore` in the line above `import Moveable from 'vue-moveable';`

**Comment by probil** [comment]
Typescript declaration added in [`v1.4.0`](https://github.com/probil/vue-moveable/releases/tag/v1.4.0).
Please check it out. If you have any issues while using library with typescript - create a new issue.
Thanks for patience
