### ISSUE TITLE
How to use methods in vue-moveable

### ISSUE THREAD

**Issue by katOstrynska** [probil/vue-moveable#84]
I would like to get information about width and height od my moveable element after scaling. I tried to use method getRect(), like showed here: https://github.com/daybrush/moveable/issues/94, but in console I got `TypeError: e.currentTarget.getRect() is not a function`

My code:
```vue
<template>
  <Moveable
    @scale="handleScale"
    @scaleEnd="(e) => {handleScaleEnd(e)}"
    ref="moveable"
  >
</template>

<script>
export default {
  methods: {
    handleScale({ target, transform, scale }) {
      target.style.transform = transform;
    },
    handleScaleEnd(e) {
      console.log(e.currentTarget.getRect());
    },
  }
}
```

How can I use methods, defined in Moveable documentation, like getRect, destroy, setState etc.

**Comment by probil** [comment]
Based on your code, I guess I can access it using `ref`:
```js
this.$refs.moveable.moveable.getRect();
```

**Comment by katOstrynska** [comment]
When I try to access it like this, I get `TypeError: this.$refs.moveable.moveable.getRect is not a function`

**Comment by probil** [comment]
@katOstrynska Check an example here
https://codesandbox.io/s/vue-moveable-demo-udvc8?fontsize=14&hidenavigation=1&theme=dark

**Comment by katOstrynska** [comment]
Nope, I still get the same error in console : `"TypeError: this.$refs.moveable.moveable.getRect is not a function"`, on mounted() or on scale(), it doesn't matter. 

Also, when in onScaleEnd : 
`handleScaleEnd({ target, currentTarget }) {
                let width = target.getBoundingClientRect().width
                let height = target.getBoundingClientRect().height

                this.$store.dispatch('UPDATE_ELEMENT', {
                    width,
                    height
                })    
            }`
I don't get the right values. My Element jumpsafter scaleEnd and is bigger than in the moment I ended scale.

**Comment by andreasvirkus** [comment]
I can confirm that `this.$refs.moveable.moveable.destory()` worked for me just fine

**Comment by probil** [comment]
Thanks @andreasvirkus

**Comment by dartanian300** [comment]
I'm having the same issue. I can console.log `this.$refs.moveable.moveable` inside of `mounted()`, but there are no methods there. Trying to call any method such as `this.$refs.moveable.moveable.getRect()` results in an error.

My code:
```
<Moveable 
        class="moveable"
        v-bind="moveable"
        @drag="handleDrag"
        @resizeStart="handleResizeStart"
        @resize="handleResize"
        @scale="handleScale"
        @rotateStart="handleRotateStart"
        @rotate="handleRotate"
        @warp="handleWarp"
        ref="moveable">
    <svg width="100%" height="100%">
        <rect width="100%" height="100%" style="fill:purple;stroke-width:3;stroke:rgb(0,0,0)" />
    </svg>
</Moveable>
```
```
mounted() {
    console.log("mounted: ", this.$refs.moveable.moveable)
}
```

The result:
![moveable refs](https://user-images.githubusercontent.com/3358537/75120196-9e86cf80-5657-11ea-970e-7db3cd585242.JPG)

**Comment by probil** [comment]
@dartanian300 I can confirm that this is happening in the latest version (v1.5.0). Try to downgrade to `v1.4.0`. It seems to be working fine.

I'll check what was changed in `moveable` because nothing changed in `vue-moveable` since then.
Thanks for your message 👍

**Comment by katOstrynska** [comment]
@probil I've opened similar issue yesterday, and I've downgraded to 1.4.0. as You said here, but I still got different problem - I can not get width and height od my element after rotate and scale. I got widh and height of its container. I saw that after rotate or scale offsetWidth and offsetHeight do not change in getRect() method. Look at issue I linked in moveable github. Thank You.

#112 
https://github.com/daybrush/moveable/issues/185#issue-570653808

**Comment by probil** [comment]
Starting from `v1.6.0`, all methods are available without extra `moveable` instance:
```diff
- this.$refs.moveable.moveable.getRect();
+ this.$refs.moveable.getRect();
```
For example:
```js
mounted() {
   console.log("getRect: ", this.$refs.moveable.getRect());
   console.log("isMoveableElement: ", this.$refs.moveable.isMoveableElement(document.body));
}
```
Here is a codesandbox with a demo:
https://codesandbox.io/s/vue-moveable-issue-84-xzblq

 (Added to README)

Please open a new issue if you still experience problems with calling moveable methods
