### ISSUE TITLE
Doesn't re-draw during scroll

### ISSUE THREAD

**Issue by probil** [probil/vue-moveable#9]
![67961267_10220012014116629_6592213142191734784_n](https://user-images.githubusercontent.com/6773202/62427377-e6b1c500-b6fa-11e9-9ee4-1d2eb6ae85b2.jpg)

Browser: safari /iOS

**Comment by daybrush** [comment]
@probil 
moveable has a container option.
If the container is not set, the position is fixed.


https://github.com/daybrush/moveable#-how-to-use

**Comment by probil** [comment]
@daybrush 
I through `container` what you pass into the moveable constructor. 

![Screen Shot 2019-08-05 at 14 02 01](https://user-images.githubusercontent.com/6773202/62460254-2f648f00-b78a-11e9-95ff-4ec794b04c73.png)

What is the reason of having `parent` and `container`? 🤔

**Comment by daybrush** [comment]
@probil 

It seems rather confusing. I'll make the vanilla moveable the same as the parent by default of the container.

parent is just the place to add a moveable element.

If the container is not set, the position is fixed and where it is added is not affected.

**Comment by hawkeye64** [comment]
But the text scrolls and the Moveable does not scroll with it -- this is the issue.

**Comment by probil** [comment]
Fixed in `v0.2.0`
