### ISSUE TITLE
Moveable Stuck when hitting bounds

### ISSUE THREAD

**Issue by buisine** [probil/vue-moveable#94]
Hi there,
my setup works well, i just implemented bounds setting like this :

```
bounds: { left: 0, right: 780, top: 0, bottom: 400},
dragArea : true,
snappable: true,
```

now IF the moveable touch a bound when dragging THEN when drag is released it becomes undraggable and stay stucked.
I am not ure this is the expected behavior, am i missing an option ?
Thanks.

**Comment by probil** [comment]
Hi, @buisine 
Could you please check if there any errors in the console?
Upgrading to the latest version of the library might help as well (a bunch of issues were fixed).

Next step is to create a sandbox with reproduction.

**Comment by buisine** [comment]
Hello, @probil 

i updated the module :

vue-moveable@1.4.0 

console is empty.

It actually goes worst, 
now if i drag once :  after the draggable is released : 
i can't drag anymore, before this was happening ONLY when hitting bounds.
please note that scaling still works.
removing bounds and the component works well.

**Comment by probil** [comment]
@buisine Hmmm. Strange I'm going to reproduce it tomorrow in the morning.
It might be a problem with moveable it self 🤔

**Comment by probil** [comment]
@buisine Here is a codesandbox where I've tried to reproduce the issue.
https://codesandbox.io/s/moveable-stuck-when-hitting-bounds-94-9sbp0
As you might noticed it works as expected. The only issue I've found during testing is that moveable doesn't move to the dragarea on load.

Could you please fork the sandbox and reproduce your issue there?

**Comment by buisine** [comment]
@probil Thanks.

I reproduced bug here :

https://codesandbox.io/s/moveable-stuck-when-hitting-bounds-94-wbpvk

handle Scale method was added  to the fork
+ resize/scale settings on moveable object.

**Comment by probil** [comment]
Thanks @buisine I'll take a look and respond you ASAP

**Comment by probil** [comment]
Hi, @buisine 
It seems I have found an issue. Moveable can't be `resizable` and `scalable` at the same time.
Provided that `resizable: true` is removed I unable to reproduce the issue anymore
https://codesandbox.io/s/moveable-stuck-when-hitting-bounds-94-usf5k
